app_name: VirtualLibrary
environment: development
debug: false
rich_logging: true
base_llm: openai
openai_model: gpt-3.5-turbo
anthropic_model: claude-3-opus
projects:
  - RB
  - SD
  - RA
include_whole_api_body: false
langchain_debug: true
conversation_memory: true
max_questions_to_remember: 3
strip_unused_jira_data: true
follow_related_jiras: true
validation_prompts_dir: validation
