app_name: VirtualLibrary
environment: development
debug: true
base_llm: openai
openai_model: gpt-3.5-turbo
anthropic_model: claude-3-opus
projects:
  - RB
  - SD
  - RA
include_whole_api_body: false
langchain_debug: false
