# Criteria definition for workflow gates

ready_for_dev:
  description: "Definition of Ready for Development"
  checklist:
    - "User story clearly defined"
    - "Acceptance criteria documented"
    - "No open blockers"

ready_for_qa:
  description: "Definition of Ready for QA"
  checklist:
    - "Code merged to default branch"
    - "Unit tests passing"
    - "Feature deployed to staging"
